# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170322_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaffaireprofile',
            name='type_utilisateur',
        ),
        migrations.RemoveField(
            model_name='prepresidentielprofile',
            name='type_utilisateur',
        ),
    ]
