# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170322_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrepAffaireProfile',
            new_name='PreposeAffaireProfile',
        ),
        migrations.RenameModel(
            old_name='PrepResidentielProfile',
            new_name='PreposeResidentielProfile',
        ),
    ]
