# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clientaffaireprofile_clientresidentielprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAffaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClientResidentiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientaffaireprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientresidentielprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientAffaireProfile',
        ),
        migrations.DeleteModel(
            name='ClientResidentielProfile',
        ),
    ]
