# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170322_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaffaire',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientaffaire',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientaffaire',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientresidentiel',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientresidentiel',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientresidentiel',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
