# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170322_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='preposeaffaireprofile',
            name='prep_type',
            field=models.CharField(default='prep_affaire', max_length=100),
        ),
        migrations.AddField(
            model_name='preposeresidentielprofile',
            name='prep_type',
            field=models.CharField(default='prep_residentiel', max_length=100),
        ),
    ]
