# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170323_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preposeresidentielprofile',
            options={'permissions': (('view_all_clients', 'can view all clients'),)},
        ),
    ]
